/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ProductList: typeof import('./src/components/vue/ProductList.vue')['default']
    PuikButton: typeof import('@prestashopcorp/puik-components')['PuikButton']
    PuikSwitch: typeof import('@prestashopcorp/puik-components')['PuikSwitch']
    PuikTable: typeof import('@prestashopcorp/puik-components')['PuikTable']
  }
}
